## this is intentional bad deployment to test kyverno policies. 
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: kyverno-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        
