apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: kyverno-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: nginx
        image: docker.io/nginxinc/nginx-unprivileged:1.25
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        
        