apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-resourcequota
spec:
  rules:
    - name: create-resourcequota
      match:
        resources:
          kinds:
            - Namespace
      generate:
        apiVersion: v1   
        kind: ResourceQuota
        name: namespace-quota
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        data:
          spec:
            hard:
              requests.cpu: "2"
              requests.memory: "2Gi"
              limits.cpu: "4"
              limits.memory: "4Gi"